[theme]
base = "light"
primaryColor = "#0F62FE"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F7"
textColor = "#161616"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
